local function readFile(path)
	local f = assert(io.open(path, "rb"))
	local text = f:read("*a")
	f:close()
	return text
end

local function scanLearnedAffixesSource()
	local source = readFile("AutoDelete.lua")
	local startAt = assert(source:find("local function ScanLearnedAffixes", 1, true))
	local endAt = assert(source:find("_G.AutoDelete_ScanLearnedAffixes", startAt, true))
	return source:sub(startAt, endAt)
end

local function affixPopupSource()
	local source = readFile("Options.lua")
	local startAt = assert(source:find("-- Learned Affixes Popup", 1, true))
	local endAt = assert(source:find("end  -- end of Learned Affixes Popup", startAt, true))
	return source:sub(startAt, endAt)
end

local function slashAffixSource()
	local source = readFile("AutoDelete.lua")
	local startAt = assert(source:find('if arg == "affix" then', 1, true))
	local endAt = assert(source:find('if arg == "scav"', startAt, true))
	return source:sub(startAt, endAt)
end

local function helpSource()
	local source = readFile("AutoDelete.lua")
	local startAt = assert(source:find('if arg == "help"', 1, true))
	local endAt = assert(source:find("_G.AutoDelete_ToggleOptionsPanel()", startAt, true))
	return source:sub(startAt, endAt)
end

describe("Affix window integration", function()
	it("keeps the affix window owned by AutoDelete instead of opening PEE", function()
		local autoDelete = readFile("AutoDelete.lua")
		local scan = scanLearnedAffixesSource()
		local options = readFile("Options.lua")
		local toc = readFile("AutoDelete.toc")

		assert.is_nil(autoDelete:find("AutoDelete_TryOpenPEAffixBook", 1, true))
		assert.is_nil(scan:find("ShowEnhancedAffixBook", 1, true))
		assert.is_not_nil(scan:find("AutoDelete_ShowLearnedAffixesWindow", 1, true))
		assert.is_nil(autoDelete:find("ExtractionService", 1, true))
		assert.is_nil(autoDelete:find("ExtractionUI", 1, true))
		assert.is_nil(options:find("ExtractionService", 1, true))
		assert.is_nil(options:find("ExtractionUI", 1, true))
		assert.is_nil(toc:find("ProjectEbonhold", 1, true))
	end)

	it("owns the learned-affix server transport instead of using PEE globals", function()
		local autoDelete = readFile("AutoDelete.lua")
		local toc = readFile("AutoDelete.toc")

		assert.is_not_nil(autoDelete:find("AutoDelete_AffixServerPrefix", 1, true))
		assert.is_not_nil(autoDelete:find('"AAM0x9"', 1, true))
		assert.is_not_nil(autoDelete:find("AutoDelete_AffixServerRequestLearned", 1, true))
		assert.is_not_nil(autoDelete:find("313", 1, true))
		assert.is_not_nil(autoDelete:find("AutoDelete_AffixServerSendLearned", 1, true))
		assert.is_not_nil(autoDelete:find("513", 1, true))
		assert.is_not_nil(autoDelete:find("AutoDelete_ParseLearnedAffixesPayload", 1, true))
		assert.is_not_nil(autoDelete:find("AutoDelete_SetLearnedAffixesFromServer", 1, true))
		assert.is_not_nil(autoDelete:find("AutoDelete_RequestServerLearnedAffixes", 1, true))
		assert.is_not_nil(autoDelete:find("AutoDelete_HandleAffixServerMessage", 1, true))
		assert.is_not_nil(autoDelete:find('scanner:RegisterEvent("CHAT_MSG_ADDON")', 1, true))
		assert.is_not_nil(autoDelete:find("RegisterAddonMessagePrefix", 1, true))
		assert.is_not_nil(autoDelete:find("SendAddonMessage", 1, true))
		assert.is_true(assert(toc:find("AffixServer%.lua")) < assert(toc:find("AutoDelete%.lua")))
	end)

	it("uses PEEv1 Affix Book geometry inside AutoDelete", function()
		local popup = affixPopupSource()

		assert.is_not_nil(popup:find("local SIDE_PANEL_WIDTH = 260", 1, true))
		assert.is_not_nil(popup:find("local SIDE_PANEL_HEIGHT = 430", 1, true))
		assert.is_not_nil(popup:find("local PANEL_INSET = 12", 1, true))
		assert.is_not_nil(popup:find("local AFFIX_LIST_ROW_HEIGHT = 20", 1, true))
		assert.is_not_nil(popup:find("local AFFIX_LIST_VISIBLE_ROWS = 9", 1, true))
		assert.is_not_nil(popup:find("local AFFIX_LIST_SCROLLBAR_WIDTH = 8", 1, true))
		assert.is_not_nil(popup:find("local AFFIX_LIST_HEIGHT = AFFIX_LIST_ROW_HEIGHT * AFFIX_LIST_VISIBLE_ROWS + AFFIX_LIST_PAD * 2", 1, true))
		assert.is_not_nil(popup:find("_G.AutoDelete_AffixBookLayout", 1, true))
	end)

	it("uses PEEv1-style controls and fixed-row list chrome", function()
		local popup = affixPopupSource()

		assert.is_not_nil(popup:find('"Affix Book"', 1, true))
		assert.is_not_nil(popup:find('"Search affixes..."', 1, true))
		assert.is_not_nil(popup:find('"UICheckButtonTemplate"', 1, true))
		assert.is_not_nil(popup:find('"Armor"', 1, true))
		assert.is_not_nil(popup:find('"Weapon"', 1, true))
		assert.is_not_nil(popup:find('"Learned"', 1, true))
		assert.is_nil(popup:find('"Missing"', 1, true))
		assert.is_not_nil(popup:find("db.affixBookFilters = db.affixBookFilters or { armor = true, weapon = true, learned = true }", 1, true))
		assert.is_not_nil(popup:find('"AutoDeleteLearnedAffixesListBox"', 1, true))
		assert.is_not_nil(popup:find("titleText:SetPoint(\"TOP\", popup, \"TOP\", 0, -8)", 1, true))
		assert.is_not_nil(popup:find("searchFrame:SetPoint(\"TOPLEFT\", popup, \"TOPLEFT\", PANEL_INSET, -50)", 1, true))
		assert.is_nil(popup:find('"AutoDeleteLearnedAffixesScroll"', 1, true))
	end)

	it("feeds PEEv1-style family metadata into the affix mirror", function()
		local scan = scanLearnedAffixesSource()

		assert.is_not_nil(scan:find("local function buildAffixBookRows", 1, true))
		assert.is_not_nil(scan:find("affixRows = buildAffixBookRows()", 1, true))
		assert.is_not_nil(scan:find("weaponOnly = family.weaponOnly", 1, true))
		assert.is_not_nil(scan:find("learned = family.learned", 1, true))
		assert.is_not_nil(scan:find("tiers = family.tiers", 1, true))
		assert.is_not_nil(scan:find("equippedCount = family.equippedCount", 1, true))
		assert.is_not_nil(scan:find("tier = AutoDelete_ExtractAffixLevel(entry.name) or tonumber(entry.difficulty)", 1, true))
		assert.is_not_nil(scan:find("AutoDelete_UniqueAffixes", 1, true))
		assert.is_not_nil(scan:find("eqTag = \" |cff00ff00(\"", 1, true))
		assert.is_not_nil(scan:find("AutoDelete_AllAffixFamilies", 1, true))
	end)

	it("renders a clipped nine-row list with a custom scrollbar", function()
		local popup = affixPopupSource()

		assert.is_not_nil(popup:find("for i = 1, AFFIX_LIST_VISIBLE_ROWS do", 1, true))
		assert.is_not_nil(popup:find("affixScrollOffset", 1, true))
		assert.is_not_nil(popup:find("scrollbar.thumb", 1, true))
		assert.is_not_nil(popup:find("UpdateAffixScrollbar", 1, true))
	end)

	it("implements PEEv1-style family selection and tier detail behavior", function()
		local popup = affixPopupSource()

		assert.is_not_nil(popup:find("local TIER_ICON_SIZE = 40", 1, true))
		assert.is_not_nil(popup:find("local TIER_ROMANS = { \"I\", \"II\", \"III\", \"IV\", \"V\" }", 1, true))
		assert.is_not_nil(popup:find("local descriptionText = MakeText", 1, true))
		assert.is_not_nil(popup:find("local tierFrame = CreateFrame", 1, true))
		assert.is_not_nil(popup:find("local tierButtons = {}", 1, true))
		assert.is_not_nil(popup:find("ShowAffixFamily", 1, true))
		assert.is_not_nil(popup:find("SelectAffixFamily", 1, true))
		assert.is_not_nil(popup:find("SelectAffixTier", 1, true))
		assert.is_not_nil(popup:find("SelectSearchResult", 1, true))
		assert.is_not_nil(popup:find("searchEdit:SetScript(\"OnEnterPressed\"", 1, true))
		assert.is_not_nil(popup:find("row._family", 1, true))
		assert.is_nil(popup:find("ShowAffixCopyBox", 1, true))
		assert.is_nil(popup:find("copyFrame", 1, true))
	end)

	it("resets search state when the affix mirror opens", function()
		local popup = affixPopupSource()
		local showAt = assert(popup:find("local function ShowLearnedAffixesWindow", 1, true))
		local refreshAt = assert(popup:find("RefreshAffixBook(not preserveSearch)", showAt, true))
		local resetAt = assert(popup:find('affixSearchText = ""', showAt, true))
		local clearAt = assert(popup:find("searchEdit:SetText", showAt, true))

		assert.is_true(resetAt < refreshAt)
		assert.is_true(clearAt < refreshAt)
	end)

	it("preserves the active search when a server packet refreshes an open mirror", function()
		local popup = affixPopupSource()
		local scan = scanLearnedAffixesSource()

		assert.is_not_nil(scan:find("preserveSearch = requestFresh == false", 1, true))
		assert.is_not_nil(popup:find("preserveSearch = bodyTextOrData.preserveSearch == true", 1, true))
		assert.is_not_nil(popup:find("RefreshAffixBook(not preserveSearch)", 1, true))
	end)

	it("describes the AD-owned PEEv1-style mirror in user-facing text", function()
		local options = readFile("Options.lua")
		local command = slashAffixSource()
		local help = helpSource()
		local readme = readFile("README.md")
		local changelog = readFile("CHANGELOG.md")
		local oldTarget = "PEE" .. "v2"
		local oldStyle = oldTarget .. "-style"

		assert.is_nil(options:find("opens the " .. oldTarget .. " Affix Book", 1, true))
		assert.is_nil(readme:find("opens " .. oldTarget .. "'s Affix Book", 1, true))
		assert.is_nil(changelog:find("opens the real " .. oldTarget .. " Affix Book", 1, true))
		assert.is_nil(options:find(oldStyle, 1, true))
		assert.is_nil(help:find(oldStyle, 1, true))
		assert.is_nil(readme:find(oldStyle, 1, true))
		assert.is_nil(changelog:find(oldStyle, 1, true))
		assert.is_not_nil(options:find("AutoDelete's server-fed PEEv1-style affix mirror with Armor, Weapon, and Learned filters", 1, true))
		assert.is_not_nil(command:find("AutoDelete_ScanLearnedAffixes", 1, true))
		assert.is_not_nil(help:find("open AutoDelete's server-fed PEEv1-style affix mirror", 1, true))
		assert.is_not_nil(readme:find("AutoDelete's PEEv1-style affix mirror", 1, true))
		assert.is_not_nil(readme:find("does not depend on PEE being loaded", 1, true))
		assert.is_not_nil(readme:find("Armor, Weapon, and Learned filters", 1, true))
		assert.is_not_nil(changelog:find("PEEv1-style Affix Book layout inside AutoDelete", 1, true))
		assert.is_not_nil(changelog:find("Armor, Weapon, and Learned filters", 1, true))
		assert.is_not_nil(changelog:find("no longer depends on PEE runtime globals", 1, true))
	end)
end)
